/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tayfuno' at '6/30/16 10:36 AM' with Gradle 2.14
 *
 * @author tayfuno, @date 6/30/16 10:36 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
