/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tayfuno' at '7/1/16 7:48 AM' with Gradle 2.14
 *
 * @author tayfuno, @date 7/1/16 7:48 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
